@startuml Voodie Class Diagram

class Foodie {

    -name: string
    -bio: string
    -recipes: [Recipe]
    -favoritedRecipes: [Recipe]
    -followers: Array
    -following: Array

    constructor(name: string)
    rateRecipe(recipe: Recipe, rating, review)
    favorite(recipe: Recipe)
    unfavorite(recipe: Recipe)
    createRecipe(recipe: Recipe)
    deleteRecipe(recipe: Recipe)
    follow(foodie: Foodie)
    unfollow(foodie: Foodie)
    getProfile();
}

class Recipe {
    -name: string
    -ingredients: Array
    -instructions: Array
    -cookTime: number
    -serves: number
    -totalRatings: number
    -reviews: Array
    -starRatings: Array
    -recipeRating: number
    -favorites: number
    -mealType: string

    constructor(name: string, ingredients: Array, instructions: Array, cookTime: number, serves: number)
    getRating();
    printRecipe();
    getAllReviews();
}


class MealPlanner {
    -breakfast: Array
    -lunch: Array
    -dinner: Array
    -calendar: Calendar

    generateMealPlan();
}

class MonthlyMealPlan {
    generateMealPlan(breakfast, lunch, dinner, month)
}

class WeeklyMealPlan {
    generateMealPlan(breakfast, lunch, dinner, week)
}

class DailyMealPlan {
    generateMealPlan(breakfast, lunch, dinner, day)
}



class Login {
   -name: string
    -email: string
    -password: string

    login(name, email, password)
}

class SignUp {
    -name: string
    -email: string
    -password: string

    constructor(name: string, email: string, password: string)
    signup(name, email, password)
}

class Profile {
    -foodie: Foodie
}

Profile "1" *-- "1" Foodie
Foodie -> Login
Foodie -> SignUp
Foodie "1" o----> "0..*" Recipe : creates/deletes, rates, un/favorites, edits, prints

MealPlanner "1" *--- "1" MonthlyMealPlan : generates
MealPlanner *--- WeeklyMealPlan : generates
MealPlanner *--- DailyMealPlan : generates
MonthlyMealPlan "1" o---- "1..4" WeeklyMealPlan
WeeklyMealPlan "4" o--- "1..30" DailyMealPlan

Foodie "1" *-- "1" MealPlanner : creates, customizes

Recipe ----> "0..*" Foodie : created/deleted by, rated by, un/favorited by, edited by, printed by

Recipe "0..*" ---o DailyMealPlan
Recipe "0..*" ---o WeeklyMealPlan
Recipe "0..*" ---o MonthlyMealPlan


@enduml