@startuml Voodie Class Diagram

class Foodie {

    +name: string
    +bio: string
    +recipes: [Recipe]
    +favoritedRecipes: [Recipe]
    +followers: Array
    +following: Array
    +diet: [String]
    +dislikes: [String]
    +preferredCuisines: [String]

    constructor(name: string)
    rateRecipe(recipe: Recipe, rating, review)
    favorite(recipe: Recipe)
    unfavorite(recipe: Recipe)
    createRecipe(recipe: Recipe)
    deleteRecipe(recipe: Recipe)
    follow(foodie: Foodie)
    unfollow(foodie: Foodie)
}

class Recipe {
    +name: string
    +ingredients: Array
    +instructions: Array
    +cookTime: number
    +serves: number
    +totalRatings: number
    +reviews: Array
    +starRatings: Array
    +recipeRating: number
    +favorites: number
    +tags: [string]

    constructor(name: string, ingredients: Array, instructions: Array, cookTime: number, serves: number)
    getRating();
}

class RecipePage {
    +recipe: Recipe

    displayRecipe(recipe: Recipe)
    editRecipe(recipe: Recipe) : Recipe
    addToMealPlanner(recipe: Recipe)
    printRecipe(recipe: Recipe)
    getAllReviews(recipe: Recipe)
}

class MealPlannerPage {

    +mealPlanner : MealPlanner
    askMealPlannerToPlanMeals(mealPlanner: MealPlanner) : DailyMealPlan
}

class MealPlanner {
    generateMealPlan(foodie: Foodie, period: Period): MonthlyMealPlan | WeeklyMealPlan | DailyMealPlan
}

class MonthlyMealPlan {
    +mealPlans: [DailyMealPlan]
}

class WeeklyMealPlan {
    +mealPlans: [DailyMealPlan]
}

class DailyMealPlan {
    +breakfast: Recipe
    +lunch: Recipe
    +dinner: Recipe
}

class InspirationPage {
    +foodies: [Foodie]
    +recipes: [Recipe]

    displayFeaturedFoodie(foodies: [Foodie])
    displayTopRecipesWeek(recipes: [Recipe])
    displaySeasonalCuisines(recipes: [Recipe])
}

class LoginPage {
    login(email: string | username: string, password: string)
}

class SignUpPage {
    signup(username: string, email: string, password: string) : Foodie
}

class ProfilePage {
    +foodie: Foodie
    displayProfile(foodie: Foodie);
}

ProfilePage "1" *-- "1" Foodie : displays

Foodie <-right- LoginPage
Foodie <-down- SignUpPage : creates
Foodie "1" o-> "0..*" Recipe : creates
Foodie "1" --> "1" MealPlanner : uses
Foodie <- InspirationPage : shows featured foodies

MealPlanner "1" -- "1" MonthlyMealPlan : generates
MealPlanner -down- WeeklyMealPlan : generates
MealPlanner - DailyMealPlan : generates
MealPlanner <-right-* MealPlannerPage : displays

MonthlyMealPlan "1" *-down- "1..30" DailyMealPlan
WeeklyMealPlan "1" *-- "1..7" DailyMealPlan

Recipe <-right- "0..*" Foodie : uses
Recipe "0..*" -o DailyMealPlan
Recipe <-down-* RecipePage : displays
Recipe <-up- InspirationPage: displays

@enduml